// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnoI0OsYLQm-IXGIWldJfYC1yg5ALPhUY',
    appId: '1:752882152849:web:dda326f53f4003c451d630',
    messagingSenderId: '752882152849',
    projectId: 'focusmate-9e315',
    authDomain: 'focusmate-9e315.firebaseapp.com',
    storageBucket: 'focusmate-9e315.firebasestorage.app',
    measurementId: 'G-WFDKSWHLB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhybHlJlV5zdfGnrFCeJm7GXBYch12XTc',
    appId: '1:752882152849:android:141b779dab53a62851d630',
    messagingSenderId: '752882152849',
    projectId: 'focusmate-9e315',
    storageBucket: 'focusmate-9e315.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwBCcTeXNnFNJCynATI37E2hpqfp3Dmg',
    appId: '1:752882152849:ios:e82db696b5eafd0351d630',
    messagingSenderId: '752882152849',
    projectId: 'focusmate-9e315',
    storageBucket: 'focusmate-9e315.firebasestorage.app',
    iosClientId: '752882152849-8582r6i8h7iva6e27nrlhql47bkps1jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwBCcTeXNnFNJCynATI37E2hpqfp3Dmg',
    appId: '1:752882152849:ios:e82db696b5eafd0351d630',
    messagingSenderId: '752882152849',
    projectId: 'focusmate-9e315',
    storageBucket: 'focusmate-9e315.firebasestorage.app',
    iosClientId: '752882152849-8582r6i8h7iva6e27nrlhql47bkps1jq.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnoI0OsYLQm-IXGIWldJfYC1yg5ALPhUY',
    appId: '1:752882152849:web:92cc09536dcc9b8d51d630',
    messagingSenderId: '752882152849',
    projectId: 'focusmate-9e315',
    authDomain: 'focusmate-9e315.firebaseapp.com',
    storageBucket: 'focusmate-9e315.firebasestorage.app',
    measurementId: 'G-MC20S19H6G',
  );
}
